#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := nokia5510.cpp

# header files in this project
HEADERS := nokia5510.hpp

# other places to look for files for this project
SEARCH  := C:\Users\Bram\Desktop\TCTI-V1OOPC-15-BASE\nokia5510

# set BMPTK to the next higher directory and defer to the Makefile.due
BMPTK := $(BMPTK)../
include $(BMPTK)Makefile.due
